baseURL = "https://yangzhanghavefun.github.io/yzzhan/"
languageCode = "en"
publishDir = "docs"
title = "Yzzhan Tech Repo"
theme = "hugo-nuo"

# enableGitInfo = true
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

hasCJKLanguage = true  # If there're Chinese/Japanese/Korean Languages in the content, enable this.
rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This is only used by RSS template.
# googleAnalytics = "UA-123-45"
# disqusShortname = "yourdiscussshortname"

[author]
  name = "Yang Zhang"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag = "tags"
  category = "Categories"  # Categories are disabled by default.

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # themeColor = "#494f5c"  # Theme color in meta tags.
  homeSubtitle = "My personal tech recording."
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  # gitUrl = "https://github.com/Someone/SomeRepo/commit/" # Prefix of link to you git commit detail page. GitInfo must be enabled. 
  justifyContent = false  # Set "text-align: justify" to .content
  # bgImg = ""  #  Homepage background-image URL


  toc = true 

  # mathjax
  mathjax = true          # see https://www.mathjax.org/                              # 是否使用mathjax（数学公式）
  mathjaxEnableSingleDollar = true                                                    # 是否使用 $...$ 即可進行inline latex渲染
  mathjaxEnableAutoNumber = false                                                       # 是否使用公式自动编号
  mathjaxUseLocalFiles = false  # You should install mathjax in `yout-site/static/lib/mathjax`

  postMetaInFooter = true

  since = "26/11/2018"            # Site creation time   

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/"

  [[params.social]]
    name = "github"
    url = "https://github.com/"

[menu]

  [[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

  [[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 10

  [[menu.main]]
    name = "Cryptography and Security"
    url = "/Cryptography and Security/"
    weight = 10

  [[menu.main]]
    name = "Amazon"
    url = "/Amazon/"
    weight = 10 

  [[menu.main]]
    name = "About"
    url = "/about-hugo/"
    weight = 20
  [[menu.main]]
    name = "tutorials"
    url = "/Tutorial/"
    weight = 20