baseurl = "https://yangzhanghavefun.github.io/yzzhan/"
title = "Yzzhan--Personal recording area"
author = "Yang Zhang"
copyright = "Copyright (c) 2017 - 2018, Yang Zhang; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-theme-learn"
publishDir = "docs"

[params]
    author = "Yang Zhang"
    locale = "en-US"
