baseURL = "https://yangzhanghavefun.github.io/yzzhan/"
languageCode = "en"
publishDir = "docs"
title = "Yzzhan Tech Repo"
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
canonifyurls = true
paginate = 3
theme = "hugo-code-editor-theme"

[params]
    author = "John Doe"
    locale = "en-US"
